Setup docker on macos

diff --git a/.github/workflows/qit-environment-test-linux.yml b/.github/workflows/qit-environment-test-linux.yml
--- a/.github/workflows/qit-environment-test-linux.yml
+++ b/.github/workflows/qit-environment-test-linux.yml
@@ -34,7 +34,7 @@ jobs:
         run: ./qit backend:add --environment="staging" --qit_secret="${{ secrets.QIT_STAGING_SECRET }}" --manager_url="https://stagingcompatibilitydashboard.wpcomstaging.com"
 
       - name: Add "qit.test" to hosts file (Linux)
-        if: matrix.os == 'ubuntu-20.04'
+        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest'
         run: sudo echo "127.0.0.1 qit.test" | sudo tee -a /etc/hosts
 
       - name: Add "qit.test" to hosts file (Windows)
@@ -45,10 +45,19 @@ jobs:
         if: matrix.os == 'macos-latest'
         run: sudo sh -c 'echo "127.0.0.1 qit.test" >> /etc/hosts'
 
+      - name: Set up Docker
+        if: matrix.os == 'macos-latest'
+        uses: crazy-max/ghaction-setup-docker@v3.0.0
+
       - name: Start environment and get URL (Unix)
         if: runner.os != 'Windows'
         run: |
+          set -e
           siteUrl=$(./qit env:up | tail -n 1)
+          if [ -z "$siteUrl" ]; then
+            echo "Failed to get site URL"
+            exit 1
+          fi
           echo "SITE_URL=$siteUrl" >> $GITHUB_ENV
 
       - name: Start environment and get URL (Windows)
