Typo and tweak to CI

diff --git a/.github/workflows/qit-environment-test-linux.yml b/.github/workflows/qit-environment-test-linux.yml
--- a/.github/workflows/qit-environment-test-linux.yml
+++ b/.github/workflows/qit-environment-test-linux.yml
@@ -41,11 +41,24 @@ jobs:
         run: sudo echo "127.0.0.1 qit.test" | sudo tee -a /etc/hosts
 
       - name: Start environment
-        # Get the "url" property of the JSON and store it in an env var
-        run: ./qit env:up --json | jq -r '.url' | tee env_url.txt
+        run: |
+          URL=$(./qit env:up --json | jq -r '.url')
+          if [ $? -ne 0 ]; then
+            echo "Failed to start environment"
+            exit 1
+          fi
+          echo "ENV_URL=$URL" >> $GITHUB_ENV
 
       - name: Test Site Up
-        run: curl -s -o /dev/null -w "%{http_code}" $(cat env_url.txt) | grep 200
+        run: |
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENV_URL)
+          if [ "$STATUS_CODE" -eq 200 ]; then
+            echo "Site is up"
+          else
+            echo "Site is not up, status code: $STATUS_CODE"
+            exit 1
+          fi
 
       - name: Query WP JSON
-        run: curl -s "$(cat env_url.txt)/wp-json"
+        run: |
+          curl -s "$ENV_URL/wp-json"
